-- ITEMS Y MASCOTA (la mascota es un tipo de item)
create table item_personalizacion (
    codigo_item   integer generated by default as identity primary key,
    nombre        varchar(100) not null,
    tipo          varchar(20)  not null
                  check (tipo in ('COLOR','TEMA','ELEMENTO_VISUAL')),
    costo_puntos  integer      not null default 0 check (costo_puntos >= 0),
    recurso       varchar(255) not null
);

create table mascota (
    codigo_item    integer primary key
                   references item_personalizacion(codigo_item) on delete cascade,
    es_por_defecto boolean not null default false
);

-- solo puede haber UNA mascota por defecto
create unique index uq_mascota_por_defecto on mascota (es_por_defecto)
    where es_por_defecto;

-- USUARIO
create table usuario (
    codigo_usuario        integer generated by default as identity primary key,
    nombre                varchar(100) not null,
    apellido              varchar(100) not null,
    email                 varchar(255) not null unique,
    password_hash         varchar(255) not null,
    foto_perfil           varchar(500),
    perfil_privado        boolean      not null default false,
    puntos                integer      not null default 0 check (puntos >= 0),
    fecha_registro        date         not null default current_date,
    codigo_mascota_activa integer      not null references mascota(codigo_item)
);

-- META
create table meta (
    codigo_meta    integer generated by default as identity primary key,
    codigo_creador integer      not null
                   references usuario(codigo_usuario) on delete cascade,
    nombre         varchar(200) not null,
    plazo          varchar(10)  not null
                   check (plazo in ('CORTO','MEDIANO','LARGO')),
    tipo           varchar(20)  not null
                   check (tipo in ('PERSONAL','PROFESIONAL','FINANCIERA','SOCIAL_FAMILIAR',
                                   'SALUD_BIENESTAR','ACADEMICA','RECREATIVA_OCIO','OTRO')),
    estado         varchar(10)  not null default 'ACTIVA'
                   check (estado in ('ACTIVA','CUMPLIDA')),
    oculta         boolean      not null default false,
    fecha_creacion date         not null default current_date
);
create index idx_meta_creador on meta (codigo_creador);

-- REGISTRO (compuesto por Meta: si se borra la meta, se borran sus registros)
create table registro (
    codigo_registro integer generated by default as identity primary key,
    codigo_meta     integer not null references meta(codigo_meta) on delete cascade,
    codigo_usuario  integer not null references usuario(codigo_usuario) on delete cascade,
    fecha_registro  date    not null default current_date,
    cumplimiento    boolean not null default false
);
create index idx_registro_meta    on registro (codigo_meta);
create index idx_registro_usuario on registro (codigo_usuario);

-- PARTICIPACION (clase de asociacion Usuario - Meta)
create table participacion (
    codigo_usuario    integer not null references usuario(codigo_usuario) on delete cascade,
    codigo_meta       integer not null references meta(codigo_meta) on delete cascade,
    estado_invitacion varchar(10) not null default 'PENDIENTE'
                      check (estado_invitacion in ('PENDIENTE','ACEPTADA','RECHAZADA')),
    fecha_cumplida    date,
    primary key (codigo_usuario, codigo_meta)
);
create index idx_participacion_meta on participacion (codigo_meta);

-- INSIGNIAS (plazo y tipo en null significan "cualquiera")
create table insignia (
    codigo_insignia   integer generated by default as identity primary key,
    nombre            varchar(100) not null unique,
    descripcion       varchar(255) not null,
    icono             varchar(255) not null,
    plazo_requerido   varchar(10)
                      check (plazo_requerido in ('CORTO','MEDIANO','LARGO')),
    tipo_requerido    varchar(20)
                      check (tipo_requerido in ('PERSONAL','PROFESIONAL','FINANCIERA','SOCIAL_FAMILIAR',
                                                'SALUD_BIENESTAR','ACADEMICA','RECREATIVA_OCIO','OTRO')),
    cantidad_requerida integer not null check (cantidad_requerida > 0)
);

-- USUARIO_INSIGNIA (clase de asociacion)
create table usuario_insignia (
    codigo_usuario  integer not null references usuario(codigo_usuario) on delete cascade,
    codigo_insignia integer not null references insignia(codigo_insignia) on delete cascade,
    fecha_obtenida  date    not null default current_date,
    primary key (codigo_usuario, codigo_insignia)
);

-- USUARIO_ITEM (clase de asociacion)
create table usuario_item (
    codigo_usuario  integer not null references usuario(codigo_usuario) on delete cascade,
    codigo_item     integer not null references item_personalizacion(codigo_item) on delete cascade,
    fecha_obtenido  date    not null default current_date,
    equipado        boolean not null default false,
    primary key (codigo_usuario, codigo_item)
);